### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hubeiluotian** [zowiezhang/STAS#2]
dear author, I couldn't find the STAS algorithm in your code, can you provide me with it, thank you very much!!!

**Comment by csr16** [comment]
Could you please specify the exact problem you are encountering with the STAS algorithm in the code? Please note that we have already provided the script to run STAS in both the MPE and A&B environments. Your detailed feedback will help us assist you more effectively.

**Comment by csr16** [comment]
Specifically, about the code of STAS algorithm could be found in model/reward_model/mard/mard.py, a class named STAS.
